### ISSUE TITLE
Toast -> alert

### ISSUE THREAD

**Issue by taran35** [pandev22/SiCSy-DarkModern#1]
remplacer :
```css
.toast-notif {
  position: fixed;
  right: 32px;
  bottom: 32px;
  min-width: 220px;
  max-width: 90vw;
  background: var(--surface-color);
  color: var(--font-color);
  border: 2px solid var(--accent-color);
  border-radius: 14px;
  box-shadow: 0 8px 32px rgba(0,0,0,0.25);
  padding: 18px 32px;
  font-size: 1rem;
  font-weight: 500;
  z-index: 9999;
  opacity: 0.98;
  animation: toastIn 0.4s cubic-bezier(0.4,0,0.2,1);
  transition: opacity 0.4s, transform 0.4s;
  pointer-events: none;
  display: flex;
  align-items: center;
  gap: 10px;
}
.toast-notif.hide {
  opacity: 0;
  transform: translateY(40px) scale(0.95);
}
@keyframes toastIn {
  from {
    opacity: 0;
    transform: translateY(40px) scale(0.95);
  }
  to {
    opacity: 0.98;
    transform: translateY(0) scale(1);
  }
}
@media (max-width: 600px) {
  .toast-notif {
    right: 8px;
    bottom: 8px;
    padding: 12px 16px;
    font-size: 0.95rem;
  }
} 
```

par: 
```css
.alert-notif {
  position: fixed;
  right: 32px;
  bottom: 32px;
  min-width: 220px;
  max-width: 90vw;
  background: var(--surface-color);
  color: var(--font-color);
  border: 2px solid var(--accent-color);
  border-radius: 14px;
  box-shadow: 0 8px 32px rgba(0,0,0,0.25);
  padding: 18px 32px;
  font-size: 1rem;
  font-weight: 500;
  z-index: 9999;
  opacity: 0.98;
  animation: alertIn 0.4s cubic-bezier(0.4,0,0.2,1);
  transition: opacity 0.4s, transform 0.4s;
  pointer-events: none;
  display: flex;
  align-items: center;
  gap: 10px;
}
.alert-notif.hide {
  opacity: 0;
  transform: translateY(40px) scale(0.95);
}
@keyframes alertIn {
  from {
    opacity: 0;
    transform: translateY(40px) scale(0.95);
  }
  to {
    opacity: 0.98;
    transform: translateY(0) scale(1);
  }
}
@media (max-width: 600px) {
  .alert-notif {
    right: 8px;
    bottom: 8px;
    padding: 12px 16px;
    font-size: 0.95rem;
  }
} 
```
